# Generated by Django 4.2.7 on 2026-01-17 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('color_theme', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'libraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_preview', models.TextField(blank=True, help_text='Preview/snippet text for card display')),
                ('content_full', models.TextField(help_text='Full content of the chapter')),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='libraries.library')),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['user', 'is_archived'], name='libraries_user_id_f0c079_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['user', 'created_at'], name='libraries_user_id_0fa208_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['library', 'is_archived'], name='chapters_library_59b754_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['library', 'updated_at'], name='chapters_library_a8be59_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['updated_at'], name='chapters_updated_43364c_idx'),
        ),
    ]
