# Generated by Django 4.2.7 on 2026-01-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='message_count',
            field=models.IntegerField(default=0, help_text='Triggers summarization every 20 messages'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary_text',
            field=models.TextField(blank=True, default='', help_text='AI-compressed summary of older messages'),
        ),
        migrations.AddField(
            model_name='library',
            name='summary_text',
            field=models.TextField(blank=True, default='', help_text='AI-generated abstract of all chapters in this library'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content_full',
            field=models.TextField(blank=True, help_text='Deprecated - use Messages for chat-based content'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content_preview',
            field=models.TextField(blank=True, help_text='Auto-generated preview'),
        ),
    ]
