# Generated by Django 4.2.7 on 2026-01-09 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('biometric_type', models.CharField(blank=True, choices=[('FACE_ID', 'Face ID'), ('FINGERPRINT', 'Fingerprint'), ('UNKNOWN', 'Unknown')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'fingerprint'], name='devices_user_id_756e48_idx'), models.Index(fields=['last_seen_at'], name='devices_last_se_ab9139_idx')],
                'unique_together': {('user', 'fingerprint')},
            },
        ),
    ]
