# Generated by Django 4.2.7 on 2026-01-09 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.CharField(choices=[('SECURITY_METHOD', 'Security Method'), ('CREATE_PASSCODE', 'Create Passcode'), ('BIOMETRIC', 'Biometric'), ('DONE', 'Done')], default='SECURITY_METHOD', max_length=20)),
                ('lock_method', models.CharField(blank=True, choices=[('PIN', 'PIN'), ('PATTERN', 'Pattern'), ('PASSWORD', 'Password')], max_length=20, null=True)),
                ('lock_enabled', models.BooleanField(default=False)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding',
                'ordering': ['-created_at'],
            },
        ),
    ]
