# Generated by Django 4.2.7 on 2026-01-20 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_chapter_message_count_chapter_summary_text_and_more'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_normalized', models.CharField(db_index=True, help_text='Lowercase, trimmed for matching', max_length=255)),
                ('aliases', models.JSONField(default=list, help_text='["Jane", "Jane Smith", "my sister Jane"]')),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('LOCATION', 'Location'), ('ORG', 'Organization'), ('EVENT', 'Event'), ('TOPIC', 'Topic/Interest'), ('DATE', 'Important Date'), ('GOAL', 'Goal/Aspiration')], max_length=20)),
                ('summary', models.TextField(blank=True, help_text='AI-consolidated summary: "Jane is user\'s sister, works in finance..."')),
                ('relationship_to_user', models.CharField(blank=True, help_text='sister, boss, best friend, hometown, etc.', max_length=100)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='-1.0 (negative) to 1.0 (positive)')),
                ('importance_score', models.FloatField(default=0.5, help_text="0.0 (rarely mentioned) to 1.0 (core to user's life)")),
                ('first_mentioned_at', models.DateTimeField(auto_now_add=True)),
                ('last_mentioned_at', models.DateTimeField(auto_now=True)),
                ('mention_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='FriendProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(default=dict, help_text='\n        {\n            "user_name": "Jason",\n            "preferred_name": "Jay",\n            "timezone": "Asia/Karachi",\n            "last_updated": "2026-01-20T14:30:00",\n            "profile_version": "2.0"\n        }\n    ')),
                ('emotional_context', models.JSONField(default=dict, help_text='\n        {\n            "current_mood": "Determined but Tired",\n            "energy_level": "Low",\n            "mood_trend": "stable",\n            "active_stressors": [\n                "Final Year Project Deadline",\n                "AWS Certification Exam"\n            ],\n            "recent_wins": [\n                "Fixed the WebSocket bug",\n                "Met Mom for lunch"\n            ],\n            "emotional_patterns": {\n                "typically_stressed_about": ["deadlines", "finances"],\n                "energized_by": ["coding wins", "family time"],\n                "calmed_by": ["walks", "music"]\n            }\n        }\n    ')),
                ('life_narrative', models.JSONField(default=dict, help_text='\n        {\n            "current_chapter_of_life": "Building the Legacy Startup while finishing University",\n            "core_values": [\n                "Family Legacy",\n                "Financial Independence", \n                "Technical Mastery"\n            ],\n            "long_term_goals": [\n                {"goal": "Launch Legacy App by June 2026", "progress": 0.4},\n                {"goal": "Save 1 Crore PKR", "progress": 0.15},\n                {"goal": "Graduate with Honors", "progress": 0.8}\n            ],\n            "life_themes": [\n                "Balancing ambition with family responsibilities",\n                "Building something meaningful",\n                "Growth through technical challenges"\n            ],\n            "key_relationships": [\n                {"name": "Mom", "role": "Primary support system"},\n                {"name": "Jane", "role": "Sister, confidant"},\n                {"name": "Ahmed", "role": "Co-founder, best friend"}\n            ]\n        }\n    ')),
                ('interaction_style', models.JSONField(default=dict, help_text='\n        {\n            "persona": "Supportive Co-founder",\n            "communication_preference": "Direct, Technical, No fluff",\n            "humor_style": "dry, tech references",\n            "encouragement_style": "realistic optimism",\n            "challenge_style": "gentle push",\n            "forbidden_topics": ["Ex-girlfriend", "Father\'s business failure"],\n            "preferred_greetings": "casual",\n            "emoji_tolerance": "moderate"\n        }\n    ')),
                ('next_session_primer', models.TextField(blank=True, default='', help_text='\n        "User is tired from coding all night. Start with a low-energy greeting. \n        If they mention the Legacy app, acknowledge the recent WebSocket bug fix \n        and ask how the testing is going. They seemed stressed about the deadline \n        last time - check in gently."\n        ')),
                ('important_dates', models.JSONField(default=list, help_text='\n        [\n            {"date": "1998-05-15", "type": "birthday", "note": "User\'s birthday"},\n            {"date": "2026-06-01", "type": "deadline", "note": "Legacy App Launch Target"},\n            {"date": "2025-11-10", "type": "loss", "note": "Grandfather passed away"},\n            {"date": "2026-01-15", "type": "achievement", "note": "Fixed major WebSocket bug"}\n        ]\n    ')),
                ('relationship_metrics', models.JSONField(default=dict, help_text='\n        {\n            "first_interaction": "2024-01-15",\n            "total_conversations": 147,\n            "total_messages": 2523,\n            "topics_explored": ["career", "family", "startup", "health"],\n            "emotional_moments_shared": 23,\n            "milestones_celebrated": 8,\n            "trust_level": 0.85,\n            "conversation_depth": "deep",\n            "achieved_milestones": ["first_steps", "getting_to_know_you", "trusted_friend"]\n        }\n    ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_profiles',
            },
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_snippet', models.TextField(help_text='Jane got promoted to VP')),
                ('confidence', models.FloatField(default=0.9)),
                ('sentiment', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='libraries.chapter')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='cognitive.entity')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='chat.message')),
            ],
            options={
                'db_table': 'entity_mentions',
                'indexes': [models.Index(fields=['entity', 'created_at'], name='entity_ment_entity__42705b_idx'), models.Index(fields=['chapter', 'entity'], name='entity_ment_chapter_b9bd8c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'name_normalized'], name='entities_user_id_f904b7_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'entity_type'], name='entities_user_id_45a6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['user', 'importance_score'], name='entities_user_id_f43640_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('user', 'name_normalized', 'entity_type')},
        ),
    ]
