# Generated by Django 4.2.7 on 2026-01-20 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0002_chapter_message_count_chapter_summary_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('USER', 'User'), ('AI', 'AI Assistant'), ('SYSTEM', 'System')], db_index=True, max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='{"emotion": "happy", "topics": ["work", "promotion"]}')),
                ('is_complete', models.BooleanField(default=True, help_text='False while AI is still generating')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='libraries.chapter')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['chapter', 'timestamp'], name='messages_chapter_cf53c7_idx'), models.Index(fields=['chapter', 'sender'], name='messages_chapter_eaef5e_idx')],
            },
        ),
    ]
